run_trimdata:
  read_raw:
    filename: 'atp_data.csv'
    rawfilepath: 'data'
  trim_columns: 
    columnlist: ['Winner', 'Loser']
  save_dataset:
    rawfilepath: 'data'
    filename: 'cleaned_atp.csv'

run_rankingstable:
  read_raw:
    rawfilepath: 'data'
    filename: 'cleaned_atp.csv'
  save_dataset:
    rawfilepath: 'data'
    filename: 'static_rankings.csv'

run_h2h_record:
  read_raw:
    rawfilepath: 'data'
    filename: 'cleaned_atp.csv'
  save_dataset:
    rawfilepath: 'data'
    filename: 'atp_h2h.csv'

run_surface_record:
  read_raw:
    rawfilepath: 'data'
    filename: 'cleaned_atp.csv'
  save_dataset:
    rawfilepath: 'data'
    filename: 'atp_winpct_surface.csv'

run_features:
  read_main:
    rawfilepath: 'data'
    filename: 'cleaned_atp.csv'
  read_h2h:
    rawfilepath: 'data'
    filename: 'atp_h2h.csv'
  read_surface:
    rawfilepath: 'data'
    filename: 'atp_winpct_surface.csv'
  select_columns:
    columnlist: [ATP, Location, Tournament, Date, Series, Court, Surface,
            Round, Best of, Winner, Loser, WRank, LRank, Wsets, Lsets]
  flip_records:
    seednumber: 8008
  save_dataset:
    rawfilepath: 'data'
    filename: 'atp_features.csv'

train_model:
  read_features:
    rawfilepath: 'data'
    filename: 'atp_features.csv'
  choose_features:
    features_to_use: [Rank_P1, Rank_P2, mp_surface_P1, mp_surface_P2, winpct_surface_P1,
        winpct_surface_P2, totalPlayed, h2h_win_pct]
    target: matchresult
  setFeatureType:
    columns: [Rank_P1, Rank_P2, mp_surface_P1, mp_surface_P2, winpct_surface_P1,
        winpct_surface_P2, totalPlayed, h2h_win_pct]
    input_type: float
  split_train_test:
    label: matchresult
    test_size: 0.25
    random_state: 42
  fit_xgboost:
    save_path: 'models/xgb_model.pkl'
    n_estimators: 150
    learning_rate: 0.1
    max_depth: 3
